// Code generated by hero.
// source: /Users/angelosvalsamis/go/src/githubscrapper/template/api.html
// DO NOT EDIT!
package template

import (
	"bytes"
	"githubscrapper/scrap"

	"github.com/shiyanhui/hero"
)

func ApiRender(doc scrap.DocDef, buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<!doctype html> <!-- Important: must specify -->
<html>
<head>
    <meta charset="utf-8"> <!-- Important: rapi-doc uses utf8 charecters -->
    <script src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>

</head>

<body>
`)
	buffer.WriteString(`
        <rapi-doc spec-url=`)
	hero.EscapeHTML(doc.URL, buffer)
	buffer.WriteString(`></rapi-doc>
    `)

	buffer.WriteString(`
</body>
</html>`)

}
