// Code generated by hero.
// source: /Users/deliodanna/goprojects/hypatia/template/api.html
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/taxibeat/hypatia/scrape"

	"github.com/shiyanhui/hero"
)

func ApiRender(doc scrape.DocDef, buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<!doctype html> <!-- Important: must specify -->
<html>
<head>
    <meta charset="utf-8"> <!-- Important: rapi-doc uses utf8 charecters -->
    <script src="/static/js/rapidoc-min.js"></script>
    <link href="/static/css/font1.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="/static/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="/static/js/jquery-3.3.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="/static/js/popper.min.js" crossorigin="anonymous"></script>
</head>

<body>
<header style="background-color: #23D2AA" class="row">
    <a href="/" class="col-1"><img src="/static/img/beat-sm.png"/></a>
    <span class="col-10 text-center" style="font-size: xx-large">HYPATIA</span>
    <img src="/static/img/hypatia.gif" height="100" class="col-1 float-right">
</header>
`)
	buffer.WriteString(`
        <rapi-doc spec-url="/spec/`)
	hero.EscapeHTML(doc.ID, buffer)
	buffer.WriteString(`" allow-spec-url-load="false"
                  allow-spec-file-load="false" header-color="#FFFFFF" allow-search="true"
                  regular-font="'Varela Round', 'Arial Rounded MT Bold', 'Helvetica Rounded' ">
        </rapi-doc>
    `)

	buffer.WriteString(`
</body>
</html>`)

}
