// Code generated by hero.
// source: /Users/angelosvalsamis/go/src/githubscrapper/template/api_list.html
// DO NOT EDIT!
package template

import (
	"bytes"
	"githubscrapper/scrap"

	"github.com/shiyanhui/hero"
)

func ApiList(docs []scrap.DocDef, buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<!doctype html> <!-- Important: must specify -->
<html>
<head>
    <meta charset="utf-8"> <!-- Important: rapi-doc uses utf8 charecters -->
    <script src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>

</head>

<body>
`)
	for _, doc := range docs {
		buffer.WriteString(`
<ul>
    <a  href='api.html?api=`)
		hero.EscapeHTML(doc.URL, buffer)
		buffer.WriteString(`'>Api Documentation for `)
		hero.EscapeHTML(doc.RepoName, buffer)
		buffer.WriteString(`</a>
</ul>
`)
	}

	buffer.WriteString(`
</body>
</html>`)

}
