apiVersion: v1
kind: Secret
metadata:
  name: {{ template "base-chart.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "base-chart.name" . }}
    helm.sh/chart: {{ include "base-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  hypatia-secret: {{ .Values.secret.GITHUB_TOKEN }}